@extends('layouts.app', ['title' => 'Hub'])

@section('head')
    @php
        $legacyAssetUrl = function (string $asset): string {
            $path = base_path('../assets/'.$asset);
            $version = is_file($path) ? '?v='.filemtime($path) : '';

            return url('/legacy-assets/'.$asset).$version;
        };

        $hubStyles = [
            'hub.css',
            'tissue.css',
            'column-collapse-fix.css',
            'shade-ui.css',
            'mlsn-progressive-disclosure.css',
            'bulk-area-modal.css',
            'water-progressive-disclosure.css',
            'water-blender.css',
            'disease-ui.css',
            'sensor-import.css',
            'sample-manager.css',
            'site-selector-ui.css',
            'site-dashboard.css',
            'nutrient-trend.css',
            'gilba-interpretation.css',
            'priority-action-queue.css',
            'gaip-decision.css',
            'gaip-evidence.css',
            'nutrition-calendar.css',
            'gaip-design-system.css',
            'gaip-mobile.css',
            'gaip-field-log.css',
        ];
    @endphp
    @foreach ($hubStyles as $style)
        <link rel="stylesheet" href="{{ $legacyAssetUrl($style) }}">
    @endforeach
@endsection

@section('body')
    @php
        $activeSite = auth()->user()?->activeSite;
        $savedLocation = [
            'name' => $activeSite?->location_name ?? '',
            'lat' => $activeSite?->latitude ?? '',
            'lon' => $activeSite?->longitude ?? '',
        ];

        $hubScripts = [
            'gilba-hub-v2.js',
            'growth-potential-engine.js',
            'nutrition-requirement-engine.js',
            'climate-engine-v2.js',
            'gaip-utils.js',
            'species-controller.js',
            'identity-enforcement.js',
            'climate-engine.js',
            'weather-resilience.js',
            'ambient-dli-engine.js',
            'ambient-dli-integration.js',
            'gaip-soil-temp-integration.js',
            'regional-profiles.js',
            'gilba-variety-traits.js',
            'uk-variety-traits.js',
            'scanturf-variety-traits.js',
            'geves-variety-traits.js',
            'bsa-variety-traits.js',
            'japan-variety-traits.js',
            'scandinavia-variety-traits.js',
            'nz-fine-fescue-traits.js',
            'gilba-storage-ns.js',
            'gaip-site-context.js',
            'gilba-storage-migrate.js',
            'location-preloader.js',
            'turf-profile-controller.js',
            'nitrogen-validator.js',
            'wear-recovery-engine-pure.js',
            'wear-recovery-integration.js',
            'overseed-multiplier.js',
            'overseed-climate-integration.js',
            'shade-engine-pure.js',
            'shade-integration.js',
            'dli-recovery-bridge.js',
            'gaip-classification-constants.js',
            'hub-tissue-v3.js',
            'tissue-engine.js',
            'tissue-interpretation.js',
            'soil-tissue-integration.js',
            'tissue-ui.js',
            'mlsn-progressive-disclosure.js',
            'mulders-interaction-checker.js',
            'hill-labs-sample-types.js',
            'ammonium-acetate-methodology.js',
            'cotula-bowling-green.js',
            'nutrient-demand-engine.js',
            'nutrition-summary-integration.js',
            'water-progressive-disclosure-WITH-SOIL-INTERACTION.js',
            'salinity-penalty.js',
            'salinity-climate-integration.js',
            'salinity-engine-pure.js',
            'recycled-water-nutrient-engine.js',
            'phytotoxicity-engine.js',
            'water-blender.js',
            'water-blender-ui.js',
            'water-importer.js',
            'au-variety-traits.js',
            'nz-variety-traits.js',
            'variety-traits-integration.js',
            'variety-selector-ui.js',
            'cultivar-profile-ui.js',
            'nz-fine-fescue-integration.js',
            'gilba-pgr-module-v3.js',
            'pgr-ui.js',
            'dmi-growth-suppression.js',
            'irrigation-scheduler.js',
            'irrigation-scheduler-ui.js',
            'climate-module-v2.js',
            'climate-module-v2-ui.js',
            'climate-module-v2.1-dual-metrics.js',
            'climate-module-v2.1-ui.js',
            'climate-module-v2.1-integration.js',
            'dew-prediction-engine.js',
            'dew-prediction-ui.js',
            'dew-prediction-integration.js',
            'tissue-progressive-disclosure.js',
            'extended-regional-fungicides.js',
            'european-regional-fungicides.js',
            'nz-fungicides.js',
            'au-fungicides.js',
            'uk-fungicides.js',
            'fungicide-filter.js',
            'smith-kerns-model.js',
            'large-patch-model.js',
            'disease-engine.js',
            'disease-engine-pure.js',
            'disease-stress-climate-coupling.js',
            'disease-ui.js',
            'disease-integration.js',
            'bipolaris-curvularia-models.js',
            'red-thread-model.js',
            'red-thread-integration.js',
            'gilba-charts.js',
            'disease-forecast.js',
            'irrigation-forecast.js',
            'shade-forecast.js',
            'pgr-forecast.js',
            'stress-trajectory-engine-pure.js',
            'stress-trajectory-ui.js',
            'stress-trajectory-integration.js',
            'hub-integration-patch.js',
            'dependency-graph.js',
            'soil-temp-logger.js',
            'pre-emergent-engine.js',
            'pre-emergent-integration.js',
            'hub-orchestrator.js',
            'citation-registry.js',
            'engine-confidence.js',
            'confidence-ui-integration.js',
            'contradiction-detector.js',
            'input-range-validator.js',
            'gaip-scenario-engine.js',
            'gaip-whatif-ui.js',
            'cascade-orchestrator.js',
            'prediction-logger.js',
            'outcome-capture-ui.js',
            'scenario-presets.js',
            'scenario-export.js',
            'sensor-api-specconnect.js',
            'sensor-import.js',
            'sensor-import-ui.js',
            'sensor-integration-manager.js',
            'sensor-api-hydrosight.js',
            'sensor-api-bridge.js',
            'sensor-integration-ui.js',
            'lab-import.js',
            'sample-manager.js',
            'sample-persistence.js',
            'zone-key.js',
            'jspdf-shim.js',
            'word-export-combined.js',
            'gaip-ical-export.js',
            'sample-switcher-ui.js',
            'bulk-area-modal.js',
            'sample-turf-profile-modal.js',
            'sample-turf-profile-bulk-modal.js',
            'site-settings-multi-site-turf-toggle.js',
            'form-ux.js',
            'lab-report-parser.js',
            'gaip-clear-data.js',
            'input-state-watcher.js',
            'soil-structure-engine.js',
            'site-selector-ui.js',
            'site-config-persistence.js',
            'site-profile-bridge.js',
            'site-switch-cleanup.js',
            'site-dashboard.js',
            'nutrient-trend.js',
            'jszip.min.js',
            'docx.min.js',
            'word-export.js',
            'chart-annotator-hub.js',
            'export-metadata.js',
            'gilba-soil-interpretation.js',
            'gilba-water-interpretation.js',
            'gilba-synthesis-interpretation.js',
            'hub-persistence.js',
            'daily-dashboard.js',
            'priority-action-queue.js',
            'gaip-decision-engine.js',
            'gaip-decision-ui.js',
            'gaip-evidence-ui.js',
            'floating-run-button.js',
            'auto-refresh.js',
            'card-layout-redesign.js',
            'tab-navigation.js',
            'quick-jump-nav.js',
            'nutrition-calendar.js',
            'prebbles-products.js',
            'nutrition-prebble-integration.js',
            'au-fertiliser-products.js',
            'nutrition-au-fertiliser-integration.js',
            'uk-fertiliser-products.js',
            'nutrition-uk-fertiliser-integration.js',
            'tissue-corrective-engine-pure.js',
            'site-setup-wizard.js',
            'hub-header-bar.js',
            'mobile-turf-sheet.js',
            'spray-log.js',
            'spray-log-ui.js',
            'spray-log-integration.js',
            'spray-log-cascade.js',
            'spray-log-print.js',
            'gilba-alerts.js',
            'uv-residual-engine.js',
            'site-settings-panel.js',
            'site-data-transfer.js',
            'environmental-utilisation-engine.js',
            'eue-integration-bridge.js',
            'gssh-operational-summary.js',
            'shade-engine.js',
            'global-solubles.js',
            'gaip-field-log-analysis.js',
            'gaip-field-log.js',
            'gaip-morning-briefing.js',
        ];
    @endphp

    <main class="content content-wide">
        @include('partials.legacy-hub-markup', ['savedLocation' => $savedLocation])
    </main>
@endsection

@section('scripts')
    @php($headLikeScripts = ['gilba-hub-v2.js', 'growth-potential-engine.js', 'nutrition-requirement-engine.js', 'climate-engine-v2.js'])

    @foreach ($hubScripts as $script)
        <script src="{{ $legacyAssetUrl($script) }}" @if (! in_array($script, $headLikeScripts, true)) defer @endif></script>
    @endforeach
@endsection
